version: '3.8'

services:
  app-blue:
    image: taqib4802/blue-green:blue  # Pull from Docker Hub
    container_name: app-blue 
    networks:
      - app_network     
    ports:
      - "8001:8000" # Blue environment
    environment:
      - FLASK_ENV=development

  app-green:
    image: taqib4802/blue-green:green  # Pull from Docker Hub
    container_name: app-green 
    networks:
      - app_network 
    ports:
      - "8002:8000" # Green environment
    environment:
      - FLASK_ENV=development

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network
    depends_on:
      - app-blue
      - app-green  

networks:
  app_network:
    driver: bridge
    name: app_network
